### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by Rundas01** [GregTech-Intergalactical/GregTech#167]
- [x] coal coke has no burn time
- [x] normal and tiny pipesizes share the same manual crafting recipe
- [x] add autoclave
- [x] IMPORTANT: recipe progress is not saved on world quit
