### ISSUE TITLE
TODO: features to implement before first alpha

### ISSUE THREAD

**Issue by Trinsdar** [GregTech-Intergalactical/GregTech#188]
features for 0.2:

- [ ] oil driling rig
- [x] oil wells
- [ ] tree harvester
- [ ] crop harvester
- [x] pump
- [ ] long distance pipes
- [ ] quadruple and nonuple fluid pipes
- [ ] fluid pipe change to gt6 sloshing system
- [ ] slight gui refacotor
- [ ] scanner
- [ ] replicator
- [ ] recycler
- [ ] machine control cover
- [ ] shutter cover

recipes for 0.2
- [ ] arc furnace/macerator recycling
- [ ] field gens
- [ ] fluid regulators

**Comment by Trinsdar** [comment]
0.2.1:

 [ ] Stone block based covers
 [ ] Override vanilla basalt texture using dynamic resource pack
 [ ] Somehow turn red alloy cables into something like red power red alloy wire for transferring redstone, soldering alloy will become the new ulv cable
 [ ] Gt6 like wrench pickup
 [ ] disable twilight uncrafting table recipes for everything gt
